name: WordPress Theme Unit test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  phpunit:
    name: WordPress ${{ matrix.wordpress }} * PHP v${{ matrix.php }} * ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-20.04 ]
        php: [ '7.0', '7.1', '7.2', '7.3', '7.4' ]
        wordpress: [ latest, nightly, '5.1' ]
        include:
          # Function get_magic_quotes_gpc() is deprecated
          - allow_failures: "true"
            php: '7.4'
            wordpress: '5.1'

    env:
      PHP_VERSION: ${{ matrix.php }}
      WP_VERSION: ${{ matrix.wordpress }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install gettext library
        run: sudo apt-get install gettext

      - name: Install Node.js package dependencies
        run: npm install

      - name: Build a theme
        run: npm run build

      - name: Setup PHP v${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, php-mysql

      - name: apt --fix-broken install for PHP 7.0
        run: sudo apt --fix-broken install
        if: ${{ matrix.php == '7.0' }}

      - name: Install mbstring library for PHP 7.0
        # require ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
        run: sudo apt-get install php7.0-mbstring
        if: ${{ matrix.php == '7.0' }}

      - name: Edit mysql.cnf for PHP 5.6
        # MySQL8.0 default-character-set is utf8mb4.
        run: |
          sudo sed -i -e "s/\[mysql\]/\[mysql\]\ndefault-character-set=utf8/" /etc/mysql/conf.d/mysql.cnf
          sudo sed -i -e "s/\[mysql\]/\[mysql\]\ncharacter_set_server=latin1/" /etc/mysql/conf.d/mysql.cnf
        if: ${{ matrix.php == '5.6' }}

      - name: Change authentication method for MySQL8.0
        # MySQL8.0 authentication method is caching_sha2_password.
        run: |
          sudo sed -i -e "s/\[mysqld\]/\[mysqld\]\ndefault_authentication_plugin=mysql_native_password/" /etc/mysql/mysql.conf.d/mysqld.cnf
        if: ${{ matrix.php == '5.6' || matrix.php == '7.0' || matrix.php == '7.1' || matrix.php == '7.2' }}

      - name: Start MySQL
        # See https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/
        run: sudo /etc/init.d/mysql start

      - name: Install PHPUnit
        run: |
          # for PHP Compatibility - https://phpunit.de/supported-versions.html
          if [[ $PHP_VERSION == "7.0" ]] ; then
            composer global require "phpunit/phpunit=5.7.*|6.*"
          # for WP_VERSION < 4.6 due to PHP Fatal error: Class 'PHPUnit_Framework_TestCase' not found
          elif [[ ${PHP_VERSION:0:1} == "7" ]] && [[ "$WP_VERSION" < 4.6* ]] ; then
            composer global require "phpunit/phpunit=5.7.*"
          # for WP_VERSION < 5.0 due to Fatal error: Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test)
          elif [[ ${PHP_VERSION:0:1} == "7" ]] && [[ "$WP_VERSION" < 5.0* ]] ; then
            composer global require "phpunit/phpunit=5.7.*|6.*"
          else
            composer global require "phpunit/phpunit=4.8.*|5.4.*|5.7.*|6.*|7.*"
          fi

      - name: Install PHPUnit Polyfills library
        run: composer global require "yoast/phpunit-polyfills=1.0.3"

      - name: Install wp tests
        run: bash bin/install-wp-tests.sh wordpress_test root root localhost $WP_VERSION

      - name: Run PHPUnit - WordPress ${{ matrix.wordpress }}
        run: phpunit
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
